export const THEME_STYLES: Record<string, any> = {
    'Default': {
        // Backgrounds
        appBg: 'bg-[#0f172a]',
        panelBg: 'bg-slate-900/50 backdrop-blur-xl',
        panelBorder: 'border-white/10',
        cardBg: 'bg-slate-800/40 backdrop-blur-sm',
        cardBorder: 'border-white/[0.07]',
        modalBg: 'bg-[#0f172a]',
        // Text
        textPrimary: 'text-white',
        textSecondary: 'text-slate-300',
        textTertiary: 'text-slate-400',
        // Aliases used by Dashboard
        heading: 'text-white',
        subtext: 'text-slate-400',
        highlight: 'text-blue-400',
        // Gradient for hero/accent text
        hoverGradient: 'from-blue-400 to-indigo-400',
        // Accent
        accent: 'text-blue-400',
        accentBg: 'bg-blue-600',
        accentBorder: 'border-blue-500/30',
        // Badges / tags
        badgeBg: 'bg-slate-800/60',
        badgeBorder: 'border-white/10',
        // Icon containers
        iconContainer: 'bg-white/8',
        statIconColor: 'text-slate-400',
        // Buttons
        buttonPrimary: 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/20',
        buttonSecondary: 'bg-white/10 hover:bg-white/15 text-white border border-white/8',
        // Sidebar nav
        activeItem: 'bg-blue-600/10 text-blue-400 border border-blue-500/30',
        inactiveItem: 'text-slate-400 hover:bg-white/5 hover:text-slate-200',
        // Inputs
        inputBg: 'bg-black/20',
        inputBorder: 'border-white/10 focus:border-blue-500/50',
    },
    'BlueSky': {
        appBg: 'bg-slate-50',
        panelBg: 'bg-white/80 backdrop-blur-xl shadow-xl',
        panelBorder: 'border-white/60',
        cardBg: 'bg-white/60 backdrop-blur-sm',
        cardBorder: 'border-blue-100',
        modalBg: 'bg-white',
        textPrimary: 'text-slate-900',
        textSecondary: 'text-slate-700',
        textTertiary: 'text-slate-500',
        heading: 'text-slate-900',
        subtext: 'text-slate-500',
        highlight: 'text-blue-600',
        hoverGradient: 'from-blue-600 to-indigo-500',
        accent: 'text-blue-600',
        accentBg: 'bg-blue-500',
        accentBorder: 'border-blue-200',
        badgeBg: 'bg-white',
        badgeBorder: 'border-blue-100',
        iconContainer: 'bg-slate-100',
        statIconColor: 'text-slate-500',
        buttonPrimary: 'bg-blue-500 hover:bg-blue-400 text-white shadow-lg shadow-blue-500/20',
        buttonSecondary: 'bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200',
        activeItem: 'bg-blue-50 text-blue-700 border border-blue-200',
        inactiveItem: 'text-slate-500 hover:bg-slate-100 hover:text-slate-700',
        inputBg: 'bg-white',
        inputBorder: 'border-slate-200 focus:border-blue-400',
    },
    'Galaxy': {
        appBg: 'bg-[#050505]',
        panelBg: 'bg-[#0a0a0a]/80 backdrop-blur-2xl',
        panelBorder: 'border-purple-500/10',
        cardBg: 'bg-[#111]/80 backdrop-blur-sm',
        cardBorder: 'border-white/[0.06]',
        modalBg: 'bg-[#0a0a0a]',
        textPrimary: 'text-white',
        textSecondary: 'text-gray-300',
        textTertiary: 'text-gray-500',
        heading: 'text-white',
        subtext: 'text-gray-500',
        highlight: 'text-purple-400',
        hoverGradient: 'from-purple-400 to-pink-400',
        accent: 'text-purple-400',
        accentBg: 'bg-purple-600',
        accentBorder: 'border-purple-500/30',
        badgeBg: 'bg-white/5',
        badgeBorder: 'border-white/10',
        iconContainer: 'bg-white/5',
        statIconColor: 'text-gray-500',
        buttonPrimary: 'bg-purple-600 hover:bg-purple-500 text-white shadow-lg shadow-purple-500/20',
        buttonSecondary: 'bg-white/10 hover:bg-white/15 text-white border border-white/8',
        activeItem: 'bg-purple-900/20 text-purple-300 border border-purple-500/30',
        inactiveItem: 'text-gray-500 hover:bg-white/5 hover:text-gray-300',
        inputBg: 'bg-[#151515]',
        inputBorder: 'border-white/10 focus:border-purple-500',
    },
    'Ocean': {
        appBg: 'bg-[#0f172a]',
        panelBg: 'bg-[#0f172a]/60 backdrop-blur-xl',
        panelBorder: 'border-cyan-500/20',
        cardBg: 'bg-[#162a42]/60 backdrop-blur-sm',
        cardBorder: 'border-cyan-500/10',
        modalBg: 'bg-[#0f172a]',
        textPrimary: 'text-cyan-50',
        textSecondary: 'text-cyan-100',
        textTertiary: 'text-cyan-200/60',
        heading: 'text-cyan-50',
        subtext: 'text-cyan-200/60',
        highlight: 'text-cyan-400',
        hoverGradient: 'from-cyan-400 to-teal-400',
        accent: 'text-cyan-400',
        accentBg: 'bg-cyan-600',
        accentBorder: 'border-cyan-500/30',
        badgeBg: 'bg-cyan-900/30',
        badgeBorder: 'border-cyan-500/20',
        iconContainer: 'bg-cyan-900/30',
        statIconColor: 'text-cyan-400/60',
        buttonPrimary: 'bg-cyan-600 hover:bg-cyan-500 text-white shadow-lg shadow-cyan-500/20',
        buttonSecondary: 'bg-cyan-900/30 hover:bg-cyan-900/50 text-cyan-100 border border-cyan-500/20',
        activeItem: 'bg-cyan-900/30 text-cyan-300 border border-cyan-500/30',
        inactiveItem: 'text-cyan-200/50 hover:bg-cyan-900/20 hover:text-cyan-100',
        inputBg: 'bg-[#0c1826]',
        inputBorder: 'border-cyan-500/30 focus:border-cyan-400',
    },
    'Nebula': {
        appBg: 'bg-[#1e0b24]',
        panelBg: 'bg-[#2e1065]/40 backdrop-blur-xl',
        panelBorder: 'border-fuchsia-500/20',
        cardBg: 'bg-[#2e1065]/40 backdrop-blur-sm',
        cardBorder: 'border-fuchsia-500/10',
        modalBg: 'bg-[#1e0b24]',
        textPrimary: 'text-fuchsia-50',
        textSecondary: 'text-fuchsia-100',
        textTertiary: 'text-fuchsia-200/60',
        heading: 'text-fuchsia-50',
        subtext: 'text-fuchsia-200/60',
        highlight: 'text-fuchsia-400',
        hoverGradient: 'from-fuchsia-400 to-pink-400',
        accent: 'text-fuchsia-400',
        accentBg: 'bg-fuchsia-600',
        accentBorder: 'border-fuchsia-500/30',
        badgeBg: 'bg-fuchsia-900/30',
        badgeBorder: 'border-fuchsia-500/20',
        iconContainer: 'bg-fuchsia-900/30',
        statIconColor: 'text-fuchsia-400/60',
        buttonPrimary: 'bg-fuchsia-600 hover:bg-fuchsia-500 text-white shadow-lg shadow-fuchsia-500/20',
        buttonSecondary: 'bg-fuchsia-900/30 hover:bg-fuchsia-900/50 text-fuchsia-100 border border-fuchsia-500/20',
        activeItem: 'bg-fuchsia-900/30 text-fuchsia-300 border border-fuchsia-500/30',
        inactiveItem: 'text-fuchsia-200/50 hover:bg-fuchsia-900/20 hover:text-fuchsia-100',
        inputBg: 'bg-[#1a0b2e]',
        inputBorder: 'border-fuchsia-500/30 focus:border-fuchsia-400',
    },
    'Vector': {
        appBg: 'bg-[#121212]',
        panelBg: 'bg-[#181818]/90 backdrop-blur-xl',
        panelBorder: 'border-white/10',
        cardBg: 'bg-[#1e1e1e] backdrop-blur-sm',
        cardBorder: 'border-white/[0.08]',
        modalBg: 'bg-[#121212]',
        textPrimary: 'text-white',
        textSecondary: 'text-gray-300',
        textTertiary: 'text-gray-500',
        heading: 'text-white',
        subtext: 'text-gray-500',
        highlight: 'text-white',
        hoverGradient: 'from-white to-gray-300',
        accent: 'text-white',
        accentBg: 'bg-white',
        accentBorder: 'border-white/20',
        badgeBg: 'bg-white/5',
        badgeBorder: 'border-white/10',
        iconContainer: 'bg-white/8',
        statIconColor: 'text-gray-500',
        buttonPrimary: 'bg-white hover:bg-gray-200 text-black shadow-lg',
        buttonSecondary: 'bg-zinc-800 hover:bg-zinc-700 text-zinc-300 border border-white/10',
        activeItem: 'bg-white text-black border border-transparent',
        inactiveItem: 'text-gray-500 hover:bg-white/10 hover:text-white',
        inputBg: 'bg-[#111]',
        inputBorder: 'border-white/10 focus:border-white',
    }
};
